name: Terraform Destroy

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Adjust to your version

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }} if stored in Secrets

      # Terraform Init (use the same backend and state as your deploy job)
      - name: Terraform Init
        run: terraform init

      # Terraform Plan Destroy (optional)
      - name: Terraform Plan Destroy
        run: terraform plan -destroy

      # Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
