name: Deploy Helm Chart

on:
  workflow_dispatch:

jobs:
  deploy_helm_chart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v2
      with:
        version: '1.24.0'  # Specify your required kubectl version

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Install yq
      run: |
        sudo apt-get install -y yq

    - name: Get Helm chart name and version
      id: helm_chart_info
      run: |
        chart_name=$(yq eval '.name' helm-chart/values.yaml)
        chart_version=$(yq eval '.version' helm-chart/values.yaml)
        echo "chart_name=${chart_name}" >> $GITHUB_ENV
        echo "chart_version=${chart_version}" >> $GITHUB_ENV

    - name: Deploy Helm chart to EKS
      run: |
        helm upgrade --install ${{ env.chart_name }} ./helm-chart \
          --set image.repository=${{ secrets.ECR_URI }}/${{ secrets.ECR_REPOSITORY }} \
          --set image.tag=${{ github.sha }} \
          --version ${{ env.chart_version }}
